export const allData = [
    {
        id: 1,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Map_of_America_by_Sebastian_Munster.JPG/450px-Map_of_America_by_Sebastian_Munster.JPG',
        header: `Discovery of the New World`,
        description: `The term "New World" is used to describe the majority of lands of Earth's Western Hemisphere, particularly the Americas. The realization of the Americas as a new continent expanded the geographical horizon of European geographers, previously limited to Afro-Eurasia. This discovery occurred during the Age of Discovery in 1492.`,
        year: 1492,
        category: "Geography",
    },
    {
        id: 2,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Magellan_Elcano_Circumnavigation-en.svg/600px-Magellan_Elcano_Circumnavigation-en.svg.png',
        header: `Circumnavigation of the Earth`,
        description: `Ferdinand Magellan's expedition between 1519 and 1522 was the first to circumnavigate the globe. This voyage proved the Earth was round and interconnected, profoundly influencing cartography and global trade.`,
        year: 1519,
        category: "Geography",
    },
    {
        id: 3,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Corrientes-oceanicas.png/660px-Corrientes-oceanicas.png',
        header: `Mapping of the Pacific Ocean`,
        description: `In the 18th century, explorers like James Cook extensively mapped the Pacific Ocean, discovering new islands and creating accurate nautical charts that improved global navigation.`,
        year: 1770,
        category: "Geography",
    },
    {
        id: 4,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/James_Weddell_Expedition.jpg/450px-James_Weddell_Expedition.jpg',
        header: `Discovery of Antarctica`,
        description: `Antarctica was discovered in 1820 by multiple expeditions, confirming the existence of the southernmost continent. This discovery expanded knowledge of Earth's landmasses and extreme environments.`,
        year: 1820,
        category: "Geography",
    },
    {
        id: 5,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Tectonic_plates_%282022%29.svg/450px-Tectonic_plates_%282022%29.svg.png',
        header: `Plate Tectonics Theory`,
        description: `The theory of plate tectonics emerged in the 20th century, revealing that Earth's lithosphere is divided into plates that move, causing earthquakes, volcanic activity, and continental drift.`,
        year: 1960,
        category: "Geography",
    },
    {
        id: 6,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Mount_Everest_as_seen_from_Drukair2_PLW_edit_Cropped.jpg/432px-Mount_Everest_as_seen_from_Drukair2_PLW_edit_Cropped.jpg',
        header: `Discovery of Mount Everest as the World’s Highest Peak`,
        description: `In 1856, Mount Everest was identified as the tallest mountain above sea level during the Great Trigonometric Survey of India, marking a milestone in geographical measurement.`,
        year: 1856,
        category: "Geography",
    },
    {
        id: 7,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Cairo_skyline%2C_Panoramic_view%2C_Egypt.jpg/390px-Cairo_skyline%2C_Panoramic_view%2C_Egypt.jpg',
        header: `Origin of the Nile River Debate`,
        description: `Explorers like John Speke and Henry Morton Stanley mapped the sources of the Nile River in the 19th century, solving one of the oldest geographic mysteries.`,
        year: 1858,
        category: "Geography",
    },
    {
        id: 8,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Amazon_River_ESA387332.jpg/375px-Amazon_River_ESA387332.jpg',
        header: `Exploration of the Amazon River`,
        description: `Francisco de Orellana’s journey in the 16th century and later scientific expeditions revealed the Amazon River’s vast ecological and geographical significance.`,
        year: 1541,
        category: "Geography",
    },
    {
        id: 9,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Northwest_passage.jpg/585px-Northwest_passage.jpg',
        header: `The Northwest Passage`,
        description: `Roald Amundsen navigated the Northwest Passage in 1906, demonstrating a sea route through the Arctic and advancing polar exploration.`,
        year: 1906,
        category: "Geography",
    },
    {
        id: 10,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Marianatrenchmap.png/435px-Marianatrenchmap.png',
        header: `Discovery of the Mariana Trench`,
        description: `The Challenger expedition in 1875 identified the Mariana Trench as the deepest part of the world’s oceans, transforming marine geography and deep-sea exploration.`,
        year: 1875,
        category: "Geography",
    },

    {
        id: 11,
        picture: '',
        header: `Pythagorean Theorem`,
        description: `A fundamental principle in geometry, the Pythagorean theorem relates the lengths of the sides of a right triangle. Discovered by ancient Greeks, it remains a cornerstone in mathematics.`,
        year: -500,
        category: "Mathematics",
    },
    {
        id: 12,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pythagorean.svg/330px-Pythagorean.svg.png',
        header: `Discovery of Zero`,
        description: `Zero, as a numeral and concept, was introduced by Indian mathematician Brahmagupta around the 7th century. It revolutionized arithmetic, algebra, and calculus.`,
        year: 628,
        category: "Mathematics",
    },
    {
        id: 13,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/GodfreyKneller-IsaacNewton-1689.jpg/221px-GodfreyKneller-IsaacNewton-1689.jpg',
        header: `Development of Calculus`,
        description: `Independently developed by Isaac Newton and Gottfried Wilhelm Leibniz, calculus transformed mathematics by introducing concepts of limits, derivatives, and integrals.`,
        year: 1665,
        category: "Mathematics",
    },
    {
        id: 14,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Prime_number_theorem_ratio_convergence.svg/450px-Prime_number_theorem_ratio_convergence.svg.png',
        header: `Prime Number Theorem`,
        description: `The Prime Number Theorem, established in the 19th century, describes the distribution of prime numbers, providing insights into number theory.`,
        year: 1896,
        category: "Mathematics",
    },
    {
        id: 15,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Diophantus-II-8-Fermat.jpg/330px-Diophantus-II-8-Fermat.jpg',
        header: `Proof of Fermat's Last Theorem`,
        description: `In 1994, Andrew Wiles proved Fermat's Last Theorem, resolving a centuries-old mathematical conjecture about integer solutions for specific equations.`,
        year: 1994,
        category: "Mathematics",
    },
    {
        id: 16,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Mirifici_Logarithmorum_canonis_Descriptio.jpg/330px-Mirifici_Logarithmorum_canonis_Descriptio.jpg',
        header: `Invention of Logarithms`,
        description: `John Napier's invention of logarithms in the early 17th century simplified complex calculations, greatly benefiting fields like astronomy and engineering.`,
        year: 1614,
        category: "Mathematics",
    },
    {
        id: 17,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Euler%27s_formula.svg/270px-Euler%27s_formula.svg.png',
        header: `Euler's Identity`,
        description: `Described as the most beautiful equation in mathematics, Euler's identity links exponential, trigonometric, and imaginary numbers in a profound way.`,
        year: 1748,
        category: "Mathematics",
    },
    {
        id: 18,
        picture: 'https://m.media-amazon.com/images/I/41qUet2wh0L._AC_UF1000,1000_QL80_.jpg',
        header: `Introduction of Group Theory`,
        description: `Évariste Galois developed group theory in the early 19th century, creating a framework for solving polynomial equations and studying symmetries.`,
        year: 1830,
        category: "Mathematics",
    },
    {
        id: 19,
        picture: 'https://th-thumbnailer.cdn-si-edu.com/qsEc7928atihwUG5wNLd_SJN-G8=/fit-in/1200x0/filters:focal(1365x816:1366x817)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/3a/70/3a70f58d-dabc-4d54-ba16-1d1548594720/2560px-fibonaccispiralsvg.jpg',
        header: `Discovery of the Fibonacci Sequence`,
        description: `The Fibonacci sequence, introduced by Leonardo of Pisa in the 13th century, describes a series of numbers with fascinating applications in nature and art.`,
        year: 1202,
        category: "Mathematics",
    },
    {
        id: 20,
        picture: 'https://miro.medium.com/v2/resize:fit:1358/1*uxFX950Y2QMHRQqunlaJCQ.png',
        header: `Non-Euclidean Geometry`,
        description: `Developed in the 19th century, non-Euclidean geometry revolutionized mathematics by challenging the parallel postulate of Euclidean geometry.`,
        year: 1823,
        category: "Mathematics",
    },
    {
        id: 21,
        picture: 'https://www.thoughtco.com/thmb/N4O4JvwvxaqegLDow7XDd7xhi9A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-637481524-7788e3dc814645379debe599283b658d.jpg',
        header: `Laws of Motion`,
        description: `Isaac Newton's three laws of motion, introduced in 1687, laid the foundation for classical mechanics and the study of motion and forces.`,
        year: 1687,
        category: "Physics",
    },
    {
        id: 22,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Spacetime_lattice_analogy.svg/330px-Spacetime_lattice_analogy.svg.png',
        header: `Theory of Relativity`,
        description: `Albert Einstein’s theories of special and general relativity revolutionized physics by describing space, time, and gravity in a completely new way.`,
        year: 1905,
        category: "Physics",
    },
    {
        id: 23,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Plasma_globe_60th.jpg/450px-Plasma_globe_60th.jpg',
        header: `Discovery of Electromagnetism`,
        description: `James Clerk Maxwell unified electricity and magnetism in the 19th century, providing a comprehensive theory of electromagnetic fields.`,
        year: 1865,
        category: "Physics",
    },
    {
        id: 24,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Hydrogen_Density_Plots.png/525px-Hydrogen_Density_Plots.png',
        header: `Quantum Mechanics`,
        description: `The development of quantum mechanics in the early 20th century by scientists like Planck, Heisenberg, and Schrödinger reshaped our understanding of atomic and subatomic particles.`,
        year: 1925,
        category: "Physics",
    },
    {
        id: 25,
        picture: 'https://wikimedia.org/api/rest_v1/media/math/render/svg/c2ad0a6d6780c3abc5247abd82bd8a2249d56ff3',
        header: `Law of Universal Gravitation`,
        description: `Isaac Newton’s discovery of the law of universal gravitation described how all masses attract one another, forming the basis for celestial mechanics.`,
        year: 1687,
        category: "Physics",
    },
    {
        id: 26,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Candidate_Higgs_Events_in_ATLAS_and_CMS.png/330px-Candidate_Higgs_Events_in_ATLAS_and_CMS.png',
        header: `Discovery of the Higgs Boson`,
        description: `In 2012, the Higgs boson particle was discovered at CERN, confirming the existence of the Higgs field and advancing the Standard Model of particle physics.`,
        year: 2012,
        category: "Physics",
    },
    {
        id: 27,
        picture: 'https://wikimedia.org/api/rest_v1/media/math/render/svg/1799e4a910c7d26396922a20ef5ceec25ca1871c',
        header: `Wave-Particle Duality`,
        description: `Proposed by Louis de Broglie, the wave-particle duality concept showed that particles like electrons exhibit both wave-like and particle-like properties.`,
        year: 1924,
        category: "Physics",
    },
    {
        id: 28,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Alpha_Decay.svg/450px-Alpha_Decay.svg.png',
        header: `Discovery of Radioactivity`,
        description: `Henri Becquerel, Marie Curie, and Pierre Curie’s work on radioactivity in the late 19th century unveiled a new phenomenon of atomic decay.`,
        year: 1896,
        category: "Physics",
    },
    {
        id: 29,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Carnot_heat_engine_2.svg/330px-Carnot_heat_engine_2.svg.png',
        header: `First Law of Thermodynamics`,
        description: `The first law of thermodynamics, formalized in the 19th century, established the principle of energy conservation, linking heat, work, and internal energy.`,
        year: 1847,
        category: "Physics",
    },
    {
        id: 30,
        picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/First_medical_X-ray_by_Wilhelm_R%C3%B6ntgen_of_his_wife_Anna_Bertha_Ludwig%27s_hand_-_18951222.jpg/300px-First_medical_X-ray_by_Wilhelm_R%C3%B6ntgen_of_his_wife_Anna_Bertha_Ludwig%27s_hand_-_18951222.jpg',
        header: `Discovery of X-Rays`,
        description: `In 1895, Wilhelm Röntgen discovered X-rays, revolutionizing medicine and leading to the development of diagnostic imaging technologies.`,
        year: 1895,
        category: "Physics",
    },
        // Technology
        {
            id: 31,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Roue_primitive.png/330px-Roue_primitive.png',
            header: `Invention of the Wheel`,
            description: `The wheel, invented around 3500 BCE, revolutionized transportation and engineering, laying the foundation for modern machinery.`,
            year: -3500,
            category: "Technology",
        },
        {
            id: 32,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PrintMus_038.jpg/330px-PrintMus_038.jpg',
            header: `Printing Press`,
            description: `Johannes Gutenberg’s invention of the printing press in the 15th century made books widely accessible and revolutionized communication.`,
            year: 1440,
            category: "Technology",
        },
        {
            id: 33,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Johann_Philipp_Reis_telephone.jpg/233px-Johann_Philipp_Reis_telephone.jpg',
            header: `Invention of the Telephone`,
            description: `Alexander Graham Bell’s telephone, patented in 1876, transformed global communication by enabling long-distance voice transmission.`,
            year: 1876,
            category: "Technology",
        },
        {
            id: 34,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Internet_map_1024_-_transparent%2C_inverted.png/225px-Internet_map_1024_-_transparent%2C_inverted.png',
            header: `The Internet`,
            description: `The creation of ARPANET in 1969, evolving into the modern internet, revolutionized information sharing and global connectivity.`,
            year: 1969,
            category: "Technology",
        },
        {
            id: 35,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Edison_Carbon_Bulb.jpg/255px-Edison_Carbon_Bulb.jpg',
            header: `Invention of the Light Bulb`,
            description: `Thomas Edison’s development of a practical light bulb in 1879 changed the way humans interact with and use energy.`,
            year: 1879,
            category: "Technology",
        },
        {
            id: 36,
            picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCYl2_-pwd4DNHWu0YFxV5OM8fC1l2iN53IA&s',
            header: `Development of Semiconductors`,
            description: `The invention of semiconductors and transistors in the mid-20th century enabled modern electronics, powering devices like computers and smartphones.`,
            year: 1947,
            category: "Technology",
        },
        {
            id: 37,
            picture: 'https://images.prismic.io/baker-tilly-www/92d3db7a-f918-4e63-b4ec-03d47e6a5d3b_Artificial+intelligence+in+palm+of+mans+hand.jpg?auto=compress,format',
            header: `Artificial Intelligence`,
            description: `The emergence of AI in the mid-20th century introduced machine learning, robotics, and transformative technologies across industries.`,
            year: 1956,
            category: "Technology",
        },
        {
            id: 38,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/3/36/United_Airlines_Boeing_777-200_Meulemans.jpg',
            header: `Invention of the Airplane`,
            description: `The Wright brothers’ successful flight in 1903 marked the beginning of modern aviation.`,
            year: 1903,
            category: "Technology",
        },
        {
            id: 39,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Crystal_Project_computer.png',
            header: `The Personal Computer`,
            description: `The development of personal computers in the 1970s revolutionized how people work, communicate, and access information.`,
            year: 1975,
            category: "Technology",
        },
        {
            id: 40,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Iridium_satellite.jpg/435px-Iridium_satellite.jpg',
            header: `Satellite Technology`,
            description: `The launch of Sputnik in 1957 ushered in the space age, enabling global communication, navigation, and scientific research.`,
            year: 1957,
            category: "Technology",
        },
    
        // Medicine
        {
            id: 41,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Sample_of_penicillin_mould_presented_by_Alexander_Fleming_to_Douglas_Macleod%2C_1935_%289672239344%29.jpg/330px-Sample_of_penicillin_mould_presented_by_Alexander_Fleming_to_Douglas_Macleod%2C_1935_%289672239344%29.jpg',
            header: `Penicillin Discovery`,
            description: `In 1928, Alexander Fleming discovered penicillin, the first antibiotic, which transformed the treatment of bacterial infections.`,
            year: 1928,
            category: "Medicine",
        },
        {
            id: 42,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/DNA_Structure%2BKey%2BLabelled.pn_NoBB.png/435px-DNA_Structure%2BKey%2BLabelled.pn_NoBB.png',
            header: `Structure of DNA`,
            description: `In 1953, Watson and Crick discovered the double-helix structure of DNA, revolutionizing genetics and molecular biology.`,
            year: 1953,
            category: "Medicine",
        },
        {
            id: 43,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Ijms-21-06582-g002.webp/330px-Ijms-21-06582-g002.webp.png',
            header: `Discovery of Vaccines`,
            description: `Edward Jenner’s smallpox vaccine in 1796 was the first vaccine, laying the foundation for immunology.`,
            year: 1796,
            category: "Medicine",
        },
        {
            id: 44,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/XRISM_in_a_nutshell_%28cropped%29.png/450px-XRISM_in_a_nutshell_%28cropped%29.png',
            header: `X-Ray Imaging`,
            description: `Wilhelm Röntgen’s discovery of X-rays in 1895 revolutionized diagnostic medicine, enabling internal imaging of the human body.`,
            year: 1895,
            category: "Medicine",
        },
        {
            id: 45,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Insulin_struct.png/375px-Insulin_struct.png',
            header: `Discovery of Insulin`,
            description: `In 1921, Frederick Banting and Charles Best discovered insulin, a lifesaving treatment for diabetes.`,
            year: 1921,
            category: "Medicine",
        },
        {
            id: 46,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/T1t2PD.jpg/390px-T1t2PD.jpg',
            header: `MRI Technology`,
            description: `The development of Magnetic Resonance Imaging (MRI) in the 1970s provided non-invasive internal body scans.`,
            year: 1977,
            category: "Medicine",
        },
        {
            id: 47,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Preoxygenation_before_anesthetic_induction.jpg/450px-Preoxygenation_before_anesthetic_induction.jpg',
            header: `Development of Anesthesia`,
            description: `The use of anesthesia in the 19th century transformed surgery by eliminating pain during procedures.`,
            year: 1846,
            category: "Medicine",
        },
        {
            id: 48,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Circulatory_System_en.svg/375px-Circulatory_System_en.svg.png',
            header: `Discovery of Blood Circulation`,
            description: `In 1628, William Harvey described the circulation of blood, revolutionizing understanding of the human body.`,
            year: 1628,
            category: "Medicine",
        },
        {
            id: 49,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/GRNA-Cas9.svg/330px-GRNA-Cas9.svg.png',
            header: `CRISPR Gene Editing`,
            description: `The development of CRISPR-Cas9 in 2012 enabled precise editing of DNA, revolutionizing genetic engineering.`,
            year: 2012,
            category: "Medicine",
        },
        {
            id: 50,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lost_towel_number_15_found.JPG/420px-Lost_towel_number_15_found.JPG',
            header: `Organ Transplantation`,
            description: `The first successful organ transplants in the mid-20th century marked a breakthrough in life-saving medicine.`,
            year: 1954,
            category: "Medicine",
        },
    
        // Food
        {
            id: 51,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Fertile_crescent_Neolithic_B_circa_7500_BC.jpg/435px-Fertile_crescent_Neolithic_B_circa_7500_BC.jpg',
            header: `Agricultural Revolution`,
            description: `The Neolithic Agricultural Revolution introduced systematic farming around 10,000 BCE, fundamentally changing human societies and food production.`,
            year: -10000,
            category: "Food",
        },
        {
            id: 52,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/20201102.Hengnan.Hybrid_rice_Sanyou-1.6.jpg/450px-20201102.Hengnan.Hybrid_rice_Sanyou-1.6.jpg',
            header: `Domestication of Rice`,
            description: `The domestication of rice around 8000 BCE in China marked a pivotal moment in agriculture, providing a staple food for billions.`,
            year: -8000,
            category: "Food",
        },
        {
            id: 53,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Vehn%C3%A4pelto_6.jpg/330px-Vehn%C3%A4pelto_6.jpg',
            header: `Domestication of Wheat`,
            description: `The domestication of wheat around 9000 BCE in the Fertile Crescent marked a key milestone in food production.`,
            year: -9000,
            category: "Food",
        },
        {
            id: 54,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Pasteurized_milk_-Japan.jpg/330px-Pasteurized_milk_-Japan.jpg',
            header: `Pasteurization`,
            description: `In the 19th century, Louis Pasteur developed pasteurization, revolutionizing food safety and storage.`,
            year: 1864,
            category: "Food",
        },
        {
            id: 55,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Cropduster_spraying_pesticides.jpg/330px-Cropduster_spraying_pesticides.jpg',
            header: `Green Revolution`,
            description: `The Green Revolution in the mid-20th century introduced high-yield crops and modern agricultural techniques, reducing global hunger.`,
            year: 1940,
            category: "Food",
        },
        {
            id: 56,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Food_into_a_refrigerator_-_20111002.jpg/330px-Food_into_a_refrigerator_-_20111002.jpg',
            header: `Refrigeration`,
            description: `The invention of refrigeration in the 19th century transformed food storage and distribution, preventing spoilage.`,
            year: 1834,
            category: "Food",
        },
        {
            id: 57,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Genetic_engineering_logo.png/225px-Genetic_engineering_logo.png',
            header: `Genetically Modified Crops`,
            description: `The development of genetically modified crops in the 20th century improved food security and crop resistance.`,
            year: 1994,
            category: "Food",
        },
        {
            id: 58,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/FMIB_34482_Making_Salmon_Cans.jpeg/330px-FMIB_34482_Making_Salmon_Cans.jpeg',
            header: `Canning Process`,
            description: `Nicolas Appert developed canning in the early 19th century, preserving food for long-term storage.`,
            year: 1810,
            category: "Food",
        },
        {
            id: 59,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/375px-Korb_mit_Br%C3%B6tchen.JPG',
            header: `Bread Baking`,
            description: `The discovery of leavening and baking bread around 8000 BCE revolutionized diets.`,
            year: -8000,
            category: "Food",
        },
        {
            id: 60,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/B_vitamin_supplement_tablets.jpg/420px-B_vitamin_supplement_tablets.jpg',
            header: `Discovery of Vitamins`,
            description: `The discovery of vitamins in the early 20th century revolutionized nutrition and health by identifying essential compounds required for human growth.`,
            year: 1912,
            category: "Food",
        },
    
        // Energy
        {
            id: 61,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Savery-engine.jpg/255px-Savery-engine.jpg',
            header: `Invention of the Steam Engine`,
            description: `The invention of the steam engine in the 18th century revolutionized energy production and powered the Industrial Revolution.`,
            year: 1765,
            category: "Energy",
        },
        {
            id: 62,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/KinderdijkWindmills.jpg/330px-KinderdijkWindmills.jpg',
            header: `Windmills`,
            description: `The invention of windmills around the 9th century revolutionized energy use for grinding and irrigation.`,
            year: 800,
            category: "Energy",
        },
        {
            id: 63,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Agricola1.jpg/330px-Agricola1.jpg',
            header: `Harnessing Water Power`,
            description: `The development of water mills in ancient Greece utilized kinetic energy for grinding and other mechanical processes.`,
            year: -200,
            category: "Energy",
        },
        {
            id: 64,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/JamesWattEngine.jpg/480px-JamesWattEngine.jpg',
            header: `Steam Engine`,
            description: `James Watt's improvements to the steam engine in the 18th century powered the Industrial Revolution.`,
            year: 1765,
            category: "Energy",
        },
        {
            id: 65,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/London_MMB_%C2%BB1E6_Lightning.jpg/390px-London_MMB_%C2%BB1E6_Lightning.jpg',
            header: `Discovery of Electricity`,
            description: `Benjamin Franklin’s experiments in the 18th century and Alessandro Volta’s battery invention laid the foundation for understanding and using electricity.`,
            year: 1800,
            category: "Energy",
        },
        {
            id: 66,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Electromagnetic_induction_-_solenoid_to_loop_-_animation.gif',
            header: `Electromagnetic Induction`,
            description: `Michael Faraday’s discovery in 1831 made it possible to generate electricity mechanically.`,
            year: 1831,
            category: "Energy",
        },
        {
            id: 67,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/2011-05-10_18-57-46_Switzerland_-_Wil_crop.jpg/330px-2011-05-10_18-57-46_Switzerland_-_Wil_crop.jpg',
            header: `Harnessing Nuclear Energy`,
            description: `The mid-20th century saw the development of nuclear reactors, providing a powerful new source of energy.`,
            year: 1942,
            category: "Energy",
        },
        {
            id: 68,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Electrical_and_Mechanical_Services_Department_Headquarters_Photovoltaics.jpg/510px-Electrical_and_Mechanical_Services_Department_Headquarters_Photovoltaics.jpg',
            header: `Solar Power`,
            description: `The development of photovoltaic cells in the 20th century harnessed sunlight for energy generation.`,
            year: 1954,
            category: "Energy",
        },
        {
            id: 69,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/ThreeGorgesDam-China2009.jpg/450px-ThreeGorgesDam-China2009.jpg',
            header: `Hydroelectric Power`,
            description: `The first hydroelectric power plant in 1882 utilized flowing water to generate electricity.`,
            year: 1882,
            category: "Energy",
        },
        {
            id: 70,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Galvanic_cell_with_no_cation_flow.svg/465px-Galvanic_cell_with_no_cation_flow.svg.png',
            header: `Battery Invention`,
            description: `Alessandro Volta’s invention of the electric battery in 1800 enabled portable energy storage.`,
            year: 1800,
            category: "Energy",
        },
    
        // Chemistry
        {
            id: 71,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Colour_18-col_PT_with_labels.png/720px-Colour_18-col_PT_with_labels.png',
            header: `Periodic Table`,
            description: `Dmitri Mendeleev’s periodic table in 1869 organized elements based on their properties, revolutionizing chemistry.`,
            year: 1869,
            category: "Chemistry",
        },
        {
            id: 72,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Atomic-orbital-clouds_spd_m0.png/420px-Atomic-orbital-clouds_spd_m0.png',
            header: `Discovery of the Electron`,
            description: `J.J. Thomson’s discovery of the electron in 1897 provided the foundation for atomic theory.`,
            year: 1897,
            category: "Chemistry",
        },
        {
            id: 73,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Sp3_hybridization_of_H2O.jpg/330px-Sp3_hybridization_of_H2O.jpg',
            header: `Chemical Bonding`,
            description: `The development of valence theory in the early 20th century explained how atoms combine to form molecules.`,
            year: 1916,
            category: "Chemistry",
        },
        {
            id: 74,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/8/87/AmmoniaSynthesisDiagram.png',
            header: `Synthesis of Ammonia`,
            description: `The Haber-Bosch process in 1909 revolutionized agriculture by enabling large-scale production of fertilizers.`,
            year: 1909,
            category: "Chemistry",
        },
        {
            id: 75,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Paul_Nadar_-_Henri_Becquerel.jpg/330px-Paul_Nadar_-_Henri_Becquerel.jpg',
            header: `Discovery of Radioactivity`,
            description: `Henri Becquerel’s discovery of radioactivity in 1896 revealed a new phenomenon in atomic decay.`,
            year: 1896,
            category: "Chemistry",
        },
        {
            id: 76,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Liquid_oxygen_in_a_beaker_4.jpg/450px-Liquid_oxygen_in_a_beaker_4.jpg',
            header: `Discovery of Oxygen`,
            description: `Joseph Priestley and Carl Scheele independently discovered oxygen in the 18th century, revolutionizing the study of gases.`,
            year: 1774,
            category: "Chemistry",
        },
        {
            id: 77,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Single_Polymer_Chains_AFM.jpg/270px-Single_Polymer_Chains_AFM.jpg',
            header: `Development of Polymers`,
            description: `The invention of synthetic polymers like nylon in the 20th century transformed industries and materials science.`,
            year: 1935,
            category: "Chemistry",
        },
        {
            id: 78,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Nucleus_drawing.svg/330px-Nucleus_drawing.svg.png',
            header: `Discovery of Atomic Nucleus`,
            description: `Ernest Rutherford’s experiments in 1911 revealed the existence of the atomic nucleus, reshaping atomic theory.`,
            year: 1911,
            category: "Chemistry",
        },
        {
            id: 79,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Acetic-acid-dissociation-3D-balls.png/330px-Acetic-acid-dissociation-3D-balls.png',
            header: `Acid-Base Theory`,
            description: `The development of acid-base theories by Arrhenius and Bronsted-Lowry in the late 19th and early 20th centuries advanced understanding of chemical reactions.`,
            year: 1884,
            category: "Chemistry",
        },
        {
            id: 80,
            picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Beta-minus_Decay.svg/540px-Beta-minus_Decay.svg.png',
            header: `Discovery of Isotopes`,
            description: `Frederick Soddy’s discovery of isotopes in 1913 revealed the existence of elements with identical atomic numbers but different masses.`,
            year: 1913,
            category: "Chemistry",
        },
];